name: Run Google Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
            git clone https://github.com/google/googletest.git
            cd googletest
            cmake -Bbuild
            cmake --build build 
            sudo cmake --build build --target install
    - name: Build tests
      run: |
        g++ -std=c++20 test/test.cpp -lgtest -lgtest_main -lgmock -lgmock_main -o test
    - name: Run tests
      run: |
        ./test
